### ISSUE TITLE
The argument type can't be assigned to the parameter type

### ISSUE THREAD

**Issue by kharitonovAL** [lcuis/search_choices#16] opened 2020-06-18 06:39 UTC
Hi! 
I'm building a web app using flutter web and got this issue when trying to implement `search_choices`:

> error: The argument type 'List<DropdownMenuItem<dynamic>> (where DropdownMenuItem is defined in /Users/ak/Library/flutter/.pub-cache/git/flutter_web-cc38319841009fcbdf632d9b03aab18d28939438/packages/flutter_web/lib/src/material/dropdown.dart)' can't be assigned to the parameter type 'List<DropdownMenuItem<dynamic>> (where DropdownMenuItem is defined in /Users/ak/Library/flutter/packages/flutter/lib/src/material/dropdown.dart)'. (argument_type_not_assignable at [mc_web_app] lib/RequestsPage/AddEditRequestPage.dart:236)

My flutter doctor is:
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale ru-RU)
    • Flutter version 1.19.0-4.1.pre at /Users/ak/Library/flutter
    • Framework revision f994b76974 (8 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ak/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

My `pubspec.yaml`:
```
name: mc_web_app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  provider: any

  service_worker: ^0.2.0
  googleapis_auth: ^0.2.3+5
  http: ^0.12.1
  intl: ^0.16.1
  search_choices: ^1.0.17

  firebase: any
  firebase_web: ^5.0.9

  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  test: ^1.14.6

dependency_overrides:
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web

  flutter_web:
    git:
      ref: cc38319
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web

  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

  firebase:
    git:
      url: https://github.com/FirebaseExtended/firebase-dart
```

My code is also below:
```dart

import 'package:search_choices/search_choices.dart';
...

  var _housesList = List<DropdownMenuItem<dynamic>>();

...

@override
  void initState() {
    if (!widget.editRequest) _db.getHouses().then((value) {
      var list = value.map((e) => DropdownMenuItem(value: e,
        child: Text('${e.city}, ${e.street}, ${e.houseNumber}'))).toList();
      _housesList = list;
    });
    super.initState();
  }

...

RaisedButton(
  child: Text('some text'),
    onPressed: () {
      SearchChoices.single(items: _housesList, onChanged: () { /*...*/ }); // ERROE GOES HERE
    },
  )
```

What this issue is about? I mean that I know that this issue appears when your `Widget` is not compatible with `flutter_web`, but [site](https://pub.dev/packages/search_choices) said that it's compatible with web.

**Comment by lcuis** [comment] 2020-06-18 18:00
Hello @kharitonovAL ,

Can you please explain why you think that the error `argument_type_not_assignable` is due to incompatibility of the search_choices plugin with flutter web?

There is a  demonstration that the `search_choices` plugin is compatible with flutter web available here:
https://searchchoices.jod.li/

The demonstration source code is the example app that works for iOS, Android and web available here:
https://github.com/lcuis/search_choices/blob/master/example/lib/main.dart

In your `initState` function, can you please replace the `_housesList` assignment by the following one in order to analyze the root cause of the issue?
```dart
    _housesList = [
      DropdownMenuItem(
        child: Text("house 1"),
        value: "house 1",
      ),
      DropdownMenuItem(
        child: Text("house 2"),
        value: "house 2",
      ),
      DropdownMenuItem(
        child: Text("house 3"),
        value: "house 3",
      ),
      DropdownMenuItem(
        child: Text("house 4"),
        value: "house 4",
      ),
    ];
```

Can you please also explain the reason why you are calling the `SearchChoices.single` constructor in the `onPressed` method of a `RaisedButton`? Is your intention to open a dialog for the user to select a house from the `_housesList`? Because if this is the case, there is no reason for this to work whether on web or not. What you could maybe try doing for this to have a chance to work would be to replace your `RaisedButton` by the `SearchChoices.single` constructor call. This way, I imagine that the `SearchChoices` selection area can be part of the build return and be displayed so that if a user clicks on it, the selection dialog can be displayed to the user.

Can you please show the exact and complete line that the error message is pointing to (`lib/RequestsPage/AddEditRequestPage.dart:236` in your comment)?

**Comment by kharitonovAL** [comment] 2020-06-19 04:00
Hi @lcuis !

> Can you please explain why you think that the error `argument_type_not_assignable` is due to incompatibility of the search_choices plugin with flutter web?

Because of this [article](https://github.com/flutter/flutter/issues/35004#issuecomment-505133512).
 
> There is a demonstration that the `search_choices` plugin is compatible with flutter web available here:
> https://searchchoices.jod.li/
> The demonstration source code is the example app that works for iOS, Android and web available here:
> https://github.com/lcuis/search_choices/blob/master/example/lib/main.dart

Thanks!
> In your `initState` function, can you please replace the `_housesList` assignment by the following one in order to analyze the root cause of the issue?

I can't, because this error not allow me build project.

> Can you please also explain the reason why you are calling the `SearchChoices.single` constructor in the `onPressed` method of a `RaisedButton`? Is your intention to open a dialog for the user to select a house from the `_housesList`? 

Yep! I have button and I'm calling `showDialod` and wanna show something like search field in this dialog. And then by `onTap` return selected value.

> ... What you could maybe try doing for this to have a chance to work would be to replace your `RaisedButton` by the `SearchChoices.single` constructor call. This way, I imagine that the `SearchChoices` selection area can be part of the build return and be displayed so that if a user clicks on it, the selection dialog can be displayed to the user.

Thanks a lot! I'll try and then will report here.

> Can you please show the exact and complete line that the error message is pointing to (`lib/RequestsPage/AddEditRequestPage.dart:236` in your comment)?

```dart
...
SearchChoices.single(items: _housesList, onChanged: () { /*...*/ }); // ERROE GOES HERE
...
```

**Comment by kharitonovAL** [comment] 2020-06-19 04:21
@lcuis , I tried to move it from `RaisedButton` and added mok `_housesList` as you recommend, and have [new error](https://take.ms/lFxDH)

**Comment by lcuis** [comment] 2020-06-19 10:06
Hi @kharitonovAL !

Thanks for your answers.

> Hi @lcuis !
> 
> > Can you please explain why you think that the error `argument_type_not_assignable` is due to incompatibility of the search_choices plugin with flutter web?
> 
> Because of this [article](https://github.com/flutter/flutter/issues/35004#issuecomment-505133512).

I understand where your understanding comes from now, thanks. I am not sure that the cause for your issue is indeed related to the use of flutter web but maybe.

> 
> > There is a demonstration that the `search_choices` plugin is compatible with flutter web available here:
> > https://searchchoices.jod.li/
> > The demonstration source code is the example app that works for iOS, Android and web available here:
> > https://github.com/lcuis/search_choices/blob/master/example/lib/main.dart
> 
> Thanks!

You're welcome.

> 
> > In your `initState` function, can you please replace the `_housesList` assignment by the following one in order to analyze the root cause of the issue?
> 
> I can't, because this error not allow me build project.

I understand that changing this will indeed not help in the analysis because your error is a compilation error somewhere else.

> 
> > Can you please also explain the reason why you are calling the `SearchChoices.single` constructor in the `onPressed` method of a `RaisedButton`? Is your intention to open a dialog for the user to select a house from the `_housesList`?
> 
> Yep! I have button and I'm calling `showDialod` and wanna show something like search field in this dialog. And then by `onTap` return selected value.

Ok, thanks.

> 
> > ... What you could maybe try doing for this to have a chance to work would be to replace your `RaisedButton` by the `SearchChoices.single` constructor call. This way, I imagine that the `SearchChoices` selection area can be part of the build return and be displayed so that if a user clicks on it, the selection dialog can be displayed to the user.
> 
> Thanks a lot! I'll try and then will report here.

Reported from next answer from you:
> @lcuis , I tried to move it from RaisedButton and added mok _housesList as you recommend, and have [new error](https://take.ms/lFxDH)

Reported from the above link:

> `The element type 'SearchChoices<dynamic>' can't be assigned to the list type 'Widget'.`

> 
> > Can you please show the exact and complete line that the error message is pointing to (`lib/RequestsPage/AddEditRequestPage.dart:236` in your comment)?
> 
> ```dart
> ...
> SearchChoices.single(items: _housesList, onChanged: () { /*...*/ }); // ERROE GOES HERE
> ...
> ```

Thanks.

I was not able to reproduce your issue. However, I was able to make the plugin work on web with the following lines:

```dart
  var _housesList = [
    DropdownMenuItem(
      child: Text("house 1"),
      value: "house 1",
    ),
    DropdownMenuItem(
      child: Text("house 2"),
      value: "house 2",
    ),
    DropdownMenuItem(
      child: Text("house 3"),
      value: "house 3",
    ),
    DropdownMenuItem(
      child: Text("house 4"),
      value: "house 4",
    ),
  ];

  String house="";
...
  @override
  Widget build(BuildContext context) {
...
SearchChoices.single(
        items: _housesList,
        value: house,
        onChanged: (value) {
          setState(() {
            house = value;
          });
        },
        isExpanded: true,
      )...
```

So, maybe, to solve your issue, you can try adding a `value: house,` to your call to the `SearchChoices.single` constructor?

**Comment by kharitonovAL** [comment] 2020-06-19 10:33
@lcuis Thanks for your answer! But compiler said that `SearchChoices<dynamic> can't be assigned to the List type Widget`.

**Comment by lcuis** [comment] 2020-06-19 10:41
Thanks.
Would it be possible fro you to share a minimalist project with this error so that I can reproduce on my machine to investigate further?

**Comment by kharitonovAL** [comment] 2020-06-19 11:51
@lcuis Yeah, sure. I’ll remove some personal data from app (Firebase credentials) and will create private repository on Bitbucket. I need you email or other id to find you there.
Also I will be appreciate for any advices and code review!
Do you agree with this kind of sharing?

**Comment by lcuis** [comment] 2020-06-19 15:03
Should work for me, thanks. My bitbucket username is atlassianjodli

**Comment by kharitonovAL** [comment] 2020-06-22 05:09
@lcuis Hi! Added you to private copy here on Github.

**Comment by lcuis** [comment] 2020-06-22 11:00
Thanks @kharitonovAL ,
Following-up there.

**Comment by lcuis** [comment] 2020-06-23 19:43
After investigations with the help of @kharitonovAL , it turns out that the root cause of the issue was related to the migration of the `flutter_web` SDK inside the flutter SDK as mentioned there:
https://github.com/flutter/flutter_web
Closing for now. Feel free to comment and reopen as needed.

**Closed by lcuis** 2020-06-23 19:43 UTC
