### ISSUE TITLE
futureSearchFn does not work with Custom Object

### ISSUE THREAD

**Issue by Thembelani-M** [lcuis/search_choices#123] opened 2024-01-25 20:56 UTC
The onChange function does not fire when you use a custom object i.e. `Location` with `futureSearchFn`

```
     futureSearchFn: (
        String? keyword,
        String? orderBy,
        bool? orderAsc,
        List<Tuple2<String, String>>? filters,
        int? pageNb,
      ) async {
        final items = await getItems!(keyword ?? '');

        final result = items
            .map(
              (item) => DropdownMenuItem<T>(
                value: item,
                child: SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: getListItemWidget!(item),
                ),
              ),
            )
            .toList();

        return Tuple2<List<DropdownMenuItem<T>>, int>(
          result,
          items.length,
        );
      },


```

The Location object does have a `toString()` method like what has been suggested in other responses.

Here is the error

```
The following _TypeError was thrown building FutureBuilder<Tuple2<List<DropdownMenuItem<dynamic>>, int>>(dirty, state: _FutureBuilderState<Tuple2<List<DropdownMenuItem<dynamic>>, int>>#65ffb):
type '_$LocationImpl' is not a subtype of type 'String'
```

**Comment by lcuis** [comment] 2024-01-26 02:21
Hi @Thembelani-M ,

Thanks for reporting this issue.

Is this error a compilation or an execution error?

Is there a line referred to by this error?

**Comment by Thembelani-M** [comment] 2024-01-26 06:02
@lcuis Thank you for the quick response. 

```
When the exception was thrown, this was the stack: 
#0      _DropdownDialogState.listWithPagination.<anonymous closure>.<anonymous closure> (package:search_choices/src/dropdown/dropdown_dialog.dart:980:58)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:47:28)
#6      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#7      _DropdownDialogState.listWithPagination.<anonymous closure> (package:search_choices/src/dropdown/dropdown_dialog.dart:981:16)
#8      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:612:55)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#22     _invoke (dart:ui/hooks.dart:172:10)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#24     _drawFrame (dart:ui/hooks.dart:140:31)
```

**Comment by faizananwerali** [comment] 2024-01-27 19:10
same issue.

type '_Map<String, String>' is not a subtype of type 'Null'


```dart
futureSearchFn: (String? keyword,
    String? orderBy,
    bool? orderAsc,
    List<Tuple2<String, String>>? filters,
    int? pageNb) async {
  try {
    var response = await http
        .get(Uri.parse(
            "${url}countries?page=${pageNb ?? 1}${(keyword == null || keyword.isEmpty) ? "" : "&name=$keyword"}"))
        .timeout(const Duration(seconds: 10));

    if (response.statusCode != 200) {
      throw Exception(
          "Failed to get data from the internet");
    }

    var data = json.decode(response.body);
    int nbResults = data["data"]["total"];
    var records =
        (data["data"]["data"] as List<dynamic>)
            .map((item) {
      return {
        "value": item?["id"].toString() ?? "",
        "name": item?["name"].toString() ?? "",
      };
    }).toList();

    print('records: $records');

    List<DropdownMenuItem> results = (records
            as List<dynamic>)
        .map<DropdownMenuItem>((item) =>
            DropdownMenuItem(
              value: item,
              child: Card(
                shape: RoundedRectangleBorder(
                  borderRadius:
                      BorderRadius.circular(4),
                  side: BorderSide(
                    color: Colors.blue,
                    width: 1,
                  ),
                ),
                margin: EdgeInsets.all(1),
                child: Padding(
                  padding:
                      const EdgeInsets.all(6),
                  child: Text("${item["name"]}"),
                ),
              ),
            ))
        .toList();
    return (Tuple2<List<DropdownMenuItem>, int>(
        results, nbResults));
  } catch (e) {
    print("Error: $e");
    throw Exception("Failed to fetch data");
  }
},
```


```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building FutureBuilder<Tuple2<List<DropdownMenuItem<dynamic>>,
int>>(dirty, state: _FutureBuilderState<Tuple2<List<DropdownMenuItem<dynamic>>, int>>#54481):
type '_Map<String, String>' is not a subtype of type 'Null'

The relevant error-causing widget was:
  FutureBuilder<Tuple2<List<DropdownMenuItem<dynamic>>, int>>
  FutureBuilder:file:///Users/faizanrupani/.pub-cache/hosted/pub.dev/search_choices-2.2.7/lib/src/dropdown/dropdown_dialog.dart:941:15

When the exception was thrown, this was the stack:
#0      _DropdownDialogState.listWithPagination.<anonymous closure>.<anonymous closure>
(package:search_choices/src/dropdown/dropdown_dialog.dart:980:58)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#7      _DropdownDialogState.listWithPagination.<anonymous closure> (package:search_choices/src/dropdown/dropdown_dialog.dart:981:16)
#8      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609:55)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#19     _invoke (dart:ui/hooks.dart:312:13)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#21     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by lcuis** [comment] 2024-02-10 20:08
Hi @faizananwerali  and @Thembelani-M ,

Sorry for the delay and the lack of answer. It is difficult for me to investigate this issue. At first sight, it looks like you have at least one DropdownMenuItem value that is not as expected (likely null).

Are your queries always behaving as intended?
Do you see circumstances when the error does not occur?

**Comment by lcuis** [comment] 2024-02-11 04:39
I understand @faizananwerali and I am really sorry about that. I wish I had all the information necessary to investigate.

I never encountered such case myself and CI with Flutster never showed any issue.

I will now close this issue.

Feel free to reopen this issue in case anyone can share a full example.

**Closed by lcuis** 2024-02-11 04:39 UTC
